### ISSUE TITLE
Some issues in code

### ISSUE THREAD

**Issue by ezh** [jakwings/node-ternary-search-trie#5]
Actually I just review forks.
That part of functionality is not critical for me, but maybe it makes sense too... Please review 2 last commits.
https://github.com/corkscrw/node-ternary-search-trie/commits/master
`searchWithinXXXDistance callback value arg bug fix`
and
`callback gets distance as 3rd arg`
Kindly make this library perfect :sparkles: ... after 5 years :raised_hands:

**Comment by iology** [comment]
The 1st commit has already been merged long ago. Now added the new feature in the 2nd one. :tada: v5.5.0

Haven't seen a good library for ternary tries in five years? ;)

**Comment by ezh** [comment]
Thank you a lot. I don't like rewrite https://github.com/tomi/vscode-rf-language-server 😄

You made the world a better place.
